import i18next from 'i18next';

i18next.init({
  fallbackLng: ['es'],
  debug: true,
  resources: {
    en: {
      translation: {
        back: "Back",
        buscar: "Search",
        loading: "Loading...",
        save: "Save",
        loadingSave: "Saving...",
        cancelar: "Cancel",
        terminar: "Finish",
        traducir: "Translate",
        reportar: "Report",
        enviarReporte: "Send Report",
        tutor: "as tutor",
        student: "Student",
        ok: "OK",
        genericHeader: "Error",
        auth: {
          login: {
            title: "Welcome",
            subtitle: "Log in to your account",
            emailLabel: "Email address",
            emailPlaceholder: "correo@alumnos.uaq.mx",
            passwordLabel: "Password",
            passwordPlaceholder: "••••••••",
            rememberMe: "Remember me",
            forgotPassword: "Forgot your password?",
            loginButton: "Log in",
            continueWith: "or continue with",
            google: "Google",
            noAccount: "Don't have an account?",
            registerHere: "Sign up here",
            errors: {
              invalidEmail: "Invalid email address",
              invalidCredential: "Incorrect credentials",
              userNotFound: "User not found",
              wrongPassword: "Wrong password",
              emailRequired: "Email is required.",
              emailInstitutional: "Use an institutional email (@alumnos.uaq.mx).",
              passwordRequired: "Password is required.",
              default: "An error occurred. Try again."
            }
          },
          register: {
            title: "Your skills",
            subtitle: "Tell us a bit more about yourself",
            careerLabel: "TRACK",
            careerPlaceholder: "Select your track",
            semesterLabel: "SEMESTER",
            semesterPlaceholder: "Select your semester",
            skillsLabel: "SKILLS",
            skillsHeader: "COMPUTER SCIENCE SKILLS",
            skillsHint: "Tap the areas where you can help",
            readyButton: "Ready",
            selectCareer: "Select your track",
            selectSemester: "Select your semester",
            errors: {
              emailInUse: "This email is already registered.",
              invalidEmail: "The email format is invalid.",
              weakPassword: "The password is too weak.",
              default: "An error occurred during registration. Try again.",
              missingCareer: "Please select your track.",
              missingSemester: "Please select your semester.",
              missingSkills: "Please select at least one skill to share.",
              missingRegistrationData: "Missing registration data. Please go back."
            }
          }
        },
        tutorial: {
          skip: "Skip",
          next: "Next",
          done: "Done",
          welcomeTitle: "Welcome to RAM",
          welcomeSubtitle: "Learn quickly how to create, manage and review your tickets.",
          messagesTitle: "Messages and Notifications",
          messagesSubtitle: "Receive real-time updates and reply from the app.",
          createTitle: "Create tickets easily",
          createSubtitle: "Select a type, add a description and send your ticket in seconds.",
          profileTitle: "Profile and settings",
          profileSubtitle: "Edit your account, change password and set your preferences."
        },
        desconocido: "Unknown user",
        eliminar: "Delete",
        dias: {
          ayer: "Yesterday",
          dom: "Sun",
          lun: "Mon",
          mar: "Tue",
          mie: "Wed",
          jue: "Thu",
          vie: "Fri",
          sab: "Sat"
        },
        mensajes: {
          titulo: "Messages",
          vacio: "You have no active conversations.",
          noEsp: "Problem not specified",
          proceder: "How do you wish to proceed?",
          elegir: "Choose what will happen with this ticket.",
          abandonar: "Abandon help",
          libera: "Free this ticket for someone else",
          finalizar: "Finalize as canceled",
          cierra: "Close the ticket permanentely",
          volver: "Return to chat",
          resuelto: "Problem solved?",
          cerrar: "The chat will be closed, and you will be able to score the help.",
          siTerminar: "Yes, finish and score",
          seguir: "Stay in the chat",
          califica: "Score the help!",
          enviar: "Submit and finalize",
          place: "Write a message...",
        },
        profile: {
          newLevel: {
            titulo: 'Congratulations!',
            mensaje: 'You have reached level {{newLevel}} - {{levelTitle}}!',
          },
          levelClimb: 'You leveled up!',
          levelName: {
            1: 'Beginner',
            2: 'Apprentice',
            3: 'Collaborator',
            4: 'Expert',
            5: 'Advanced Mentor',
            6: 'Master',
            7: 'Legend',
            8: 'Icon',
            9: 'Deity',
            10: 'Eternal',
            11: 'Immortal',
            12: 'Supreme',
            13: 'Omniscient',
            14: 'Transcendent',
            15: 'Divine',
          },
          nivel: 'Level',
          activeSince: 'Active since {{- date}}',
          semestre: 'Semester',
          puntos: 'Points',
          faltan: 'Missing {{puntos}} points for next level',
          habilidades: 'SKILLS',
          estadisticas: {
            titulo: 'STATISTICS',
            ayuda: 'Help given',
            calificacion: 'Rating',
            solicitudes: 'Help requested',
          },
          seeMore: 'See more',
          seeLess: 'See less',
          edit: {
            titulo: "Edit profile",
            foto: "Edit photo",
            nombre: "NAME",
            nombrePlace: "Your full name",
            carrera: "TRACK",
            semestre: "SEMESTER",
            habilidades: "SKILLS",
            selecciona: "Select the areas in which you can help",
            guardar: "Save Changes",
            selectCarrera: "Select your track",
            selectSemestre: "Select your semester",
            password: "Change password",
            proteger: "To protect your account, please verify your current password first.",
            actual: "CURRENT PASSWORD",
            nueva: "NEW PASSWORD",
            minimo: "Minimum 8 characters",
            confirmar: "CONFIRM NEW PASSWORD",
            repite: "Repeat new password",
            actualizar: "Update Password",
            req: {
              caracteres: "8+ characters",
              mayu: "Uppercase",
              minu: "Lowercase",
              numero: "Number",
              simbolo: "Symbol"
            },
            coinciden: "✓ The passwords match",
            noCoinciden: "✗ The passwords don't match yet",
            error: {
              currentRequired: "Enter your current password.",
              newRequired: "Enter a new password.",
              minLength: "Must have at least 8 characters.",
              requirements: "Include uppercase, lowercase, number and symbol.",
              confirmRequired: "Confirm your new password.",
              noMatch: "Passwords do not match.",
              currentIncorrect: "The current password is incorrect.",
              sessionExpiredTitle: "Session expired",
              sessionExpiredMessage: "For security, log in again and try again.",
              generic: "Could not change the password. Please try again."
            },
            successPasswordTitle: "Password updated!",
            successPasswordMessage: "Your password has been changed successfully.",
            strength: {
              debil: "Weak",
              regular: "Regular",
              buena: "Good",
              fuerte: "Strong"
            }
          },
          cerrarSesion: "Close session",
          cerrarConfirmacion: "Are you sure you want to close session on this account?",
          si: "Yes, close",
          errorCerrar: "The session could not be closed.",
          eliminar: "Delete account",
          eliminarConfirmacion: "This action is irreversible. Are you sure you want to delete your account?",
          student: "Student",
          carrera: {
            li: 'Computer Science',
            lati: 'IT Administration',
            sof: 'Software Engineering',
            ic: 'Computer Engineering',
            itr: 'Telecommunication and Networks Engineering',
            cad: 'Data Science and Analytics Engineering',
            itic: 'IT and Cybersecurity Engineering',
          }
        },
        home: {
          filtro: 'Filter your search',
          noneFound: "No tickets were found with those filters.",
        },
        settings: {
          titulo: "Settings",
          cuenta: {
            titulo: "ACCOUNT",
            editar: "Edit personal information",
            cont: "Change password",
            cont2: "Password",
            idioma: "Language"
          },
          notificaciones: {
            titulo: "NOTIFICATIONS",
            push: "Push notificationa",
            tickets: "Tickets that match",
            insignias: "New insignias",
            mensajes: "New messages"
          },
          legal: {
            titulo: "LEGAL",
            terminos: "Terms and Conditions",
            politicas: "Privacy Policies"
          },
          cerrar: "Close Session",
          languageUpdatedTitle: "Done!",
          languageUpdatedSuccess: "Your profile was updated successfully.",
          languageUpdatedError: "Could not save your profile. Please try again.",
          eliminar: {
            titulo: "ACCOUNT",
            eliminar: "Delete Account"
          }
        },
        tickets: {
          titulo: "My Tickets",
          gestiona: "Manage your requests and help",
          activos: "active",
          solicite: "Requests",
          ayudando: "Helping",
          historial: "History",
          permanente: "This action is permanent and cannot be undone",
          eliminar: "Yes, delete",
          masAyuda: "Do you need more help?",
          nuevo: "Create new ticket",
          sinActivas: "You still don't have any active requests",
          sinAyudas: "You are not currently helping anyone",
          explorar: "Explore tickets",
          tuHistorial: "Your history will appear here",
          apoyo: "I'll help you!",
          reporte: "Why do you consider that this ticket is inappropriate?",
          reporteDesc: "Describe what happened...",
          enChat: "In chat",
          irChat: "Go to chat",
          abandonar: "Abandon",
          asignada: "Asigned",
          sinVol: "No volunteer so far",
          ayudaPor: "Helped by ",
          editar: "See and edit",
          ayude: "Helped",
          valoracion: "See score received"
        },
        crear: {
          titulo: "Ask For Help",
          subtitulo: "Create your ticket",
          subtexto: "Someone on campus can help",
          tituloProblema: "PROBLEM TITLE",
          tituloPlace: "Eg: I don't understand recursivity in Python",
          tituloDesc: "DETAILED DESCRIPTION",
          descPlace: "Explain your question in detail. The more info there is, the easier it is to help...",
          urgencia: "URGENCY",
          tags: "TAGS (MAX. 3)",
          crear: "Create request"
        },
        error: {
          atencion: "Attention",
          seleccionMin: "Please select at least one tag for the request.",
          faltanDatos: "Missing fields for the registration.",
          seleccionUrgencia: "Please select a level of urgency.",
          sinId: "Could not find the ID of the ticket to update.",
          reporte: "Please select a reason for reporting.",
          reportando: "Reporting:",
          envio: "Report sent",
          recibido: "We have received your report and we will revise it soon.",
        },
        edit: {
          titulo: "Edit your ticket",
          subtitulo: "Modify the details of your request for help",
          guardar: "Save Changes",
          exito: "Edited correctly",
          exitoMensaje: "Your changes have been saved."
        },
        prioridad: {
          alta: "High",
          media: "Medium",
          baja: "Low",
          normal: "Normal"
        },
        tiempo: {
          segundos: "{{- segundos}} seconds ago",
          minutos: "{{- minutos}} minutes ago",
          horas: "{{- horas}} hours ago",
          dias: "{{- dias}} days ago",
        },
        badges: {
          firstHelp: "First Help",
          firstHelpDesc: "Give your first help.",
          firstRequest: "First Request",
          firstRequestDesc: "Request help for the first time.",
          helper5: "Supportive",
          helper5Desc: "Help 5 peers.",
          dedicado: "Dedicated",
          dedicadoDesc: "Help a total of 10 times",
          top: "Top Tutor",
          topDesc: "Help a total of 25 times.",
          helper50: "Campus Legend",
          helper50Desc: "Help 50 peers.",
          helper100: "Academic Pillar",
          helper100Desc: "Help 100 peers. Incredible dedication.",
          estrellas: "5 Stars",
          estrellasDesc: "Maintain a score of 5.0",
          rating45: "Excellence",
          rating45Desc: "Maintain an average rating ≥ 4.5 with at least 5 helps.",
          perfect10: "Perfectionist",
          perfect10Desc: "Receive a perfect rating (5 stars) in 10 consecutive helps.",
          streak3: "On a Streak",
          streak3Desc: "Resolve 3 tickets in a row without abandoning.",
          rachaSiete: "On Streak x7",
          rachaSieteDesc: "Help with seven consecutive tickets.",
          streak15: "Unstoppable",
          streak15Desc: "Resolve 15 tickets in a row without abandoning.",
          rapida: "Fast Response",
          rapidaDesc: "Resolve a ticket in less than 5 minutes.",
          speedDemon: "Speed Demon",
          speedDemonDesc: "Resolve 10 tickets within the time limit (speed bonus).",
          expertoDB: "Expert in DB",
          expertoDBDesc: "Resolve 5 database tickets.",
          mathExpert: "Mathematician",
          mathExpertDesc: "Resolve 5 Math tickets.",
          programmingExpert: "Dev Ninja",
          programmingExpertDesc: "Resolve 5 Programming tickets.",
          polymath: "Polymath",
          polymathDesc: "Resolve at least 1 ticket in 5 different categories.",
          level3: "Certified Expert",
          level3Desc: "Reach level 3 (Expert).",
          nivelCinco: "Level 5",
          nivelCincoDesc: "Reach level 5.",
          level6: "Campus Hero",
          level6Desc: "Reach the maximum level (Hero).",
          points100: "First Hundred",
          points100Desc: "Accumulate 100 points.",
          points500: "Half a Thousand",
          points500Desc: "Accumulate 500 points.",
          points1000: "Golden Thousand",
          points1000Desc: "Accumulate 1000 points.",
          rescuer: "Rescuer",
          rescuerDesc: "Resolve a High priority ticket as a new user (< 100 pts).",
          comeback: "Resilience",
          comebackDesc: "Help again after a penalty.",
          nightOwl: "Night Owl",
          nightOwlDesc: "Resolve 3 tickets between 10 PM and 2 AM.",
          desbloq: "Insignia unlocked!",
          req: "Requirement:"
        },
        notif: {
          titulo: "Notifications",
          sinNotif: "You don't have any notifications yet.",
          mensaje: {
            titulo: "Someone wants to help you! 🚀",
            desc: "Your request has been taken: \"{{ticket}}\""
          },
          match: {
            titulo: "A request that matches your skills",
            desc: "Someone needs help with: {{tags}}"
          }
        },
        skills: {
          programming: 'Programming',
          python: 'Python',
          algebra: 'Algebra',
          calculus: 'Calculus',
          design: 'Design',
          javascript: 'JavaScript',
          algorithms: 'Algorithms',
          reactNative: 'React Native',
          nodejs: 'Node.js',
          uxui: 'UX/UI',
          figma: 'Figma',
          recursion: 'Recursion',
          java: 'Java',
          express: 'Express',
          database: 'Database',
          sql: 'SQL',
          nosql: 'NoSQL',
          aws: 'AWS',
          octave: 'Octave',
        },
        reporte: {
          contenido: 'Inappropriate or adult content',
          solicita: 'Charges a price for help',
          lenguaje: 'Offensive language',
          spam: 'Spam or false content',
          otro: 'Other',
        }
      },
    },
    es: {
      translation: {
        back: "Regresar",
        buscar: "Buscar",
        loading: "Cargando...",
        save: "Guardar",
        loadingSave: "Guardando...",
        cancelar: "Cancelar",
        terminar: "Terminar",
        traducir: "Traducir",
        reportar: "Reportar",
        enviarReporte: "Enviar Reporte",
        tutor: "como tutor",
        student: "Estudiante",
        ok: "OK",
        genericHeader: "Error",
        auth: {
          login: {
            title: "Bienvenido",
            subtitle: "Inicia sesión en tu cuenta",
            emailLabel: "Correo electrónico",
            emailPlaceholder: "correo@alumnos.uaq.mx",
            passwordLabel: "Contraseña",
            passwordPlaceholder: "••••••••",
            rememberMe: "Recordarme",
            forgotPassword: "¿Olvidaste tu contraseña?",
            loginButton: "Iniciar sesión",
            continueWith: "o continúa con",
            google: "Google",
            noAccount: "¿No tienes una cuenta?",
            registerHere: "Regístrate aquí",
            errors: {
              invalidEmail: "Correo inválido",
              invalidCredential: "Credenciales incorrectas",
              userNotFound: "Usuario no encontrado",
              wrongPassword: "Contraseña incorrecta",
              default: "Ocurrió un error. Intenta de nuevo."
            }
          },
          register: {
            title: "Tus habilidades",
            subtitle: "Cuéntanos un poco más sobre ti",
            careerLabel: "CARRERA",
            careerPlaceholder: "Selecciona tu carrera",
            semesterLabel: "SEMESTRE",
            semesterPlaceholder: "Selecciona tu semestre",
            skillsLabel: "HABILIDADES",
            skillsHeader: "HABILIDADES (INFORMÁTICA)",
            skillsHint: "Toca las áreas en las que puedes apoyar",
            readyButton: "Listo",
            selectCareer: "Selecciona tu carrera",
            selectSemester: "Selecciona tu semestre",
            errors: {
              emailInUse: "Este correo ya está registrado.",
              invalidEmail: "El formato del correo es inválido.",
              weakPassword: "La contraseña es muy débil.",
              default: "Ocurrió un error al registrar. Intenta de nuevo.",
              missingCareer: "Por favor selecciona tu carrera.",
              missingSemester: "Por favor selecciona tu semestre.",
              missingSkills: "Por favor selecciona al menos una habilidad para compartir.",
              missingRegistrationData: "Faltan datos de registro. Por favor vuelve al paso anterior."
            }
          }
        },
        tutorial: {
          skip: "Saltar",
          next: "Siguiente",
          done: "Listo",
          welcomeTitle: "Bienvenido a RAM",
          welcomeSubtitle: "Aprende rápido cómo crear, gestionar y revisar tus tickets.",
          messagesTitle: "Mensajes y notificaciones",
          messagesSubtitle: "Recibe actualizaciones en tiempo real y responde desde la app.",
          createTitle: "Crea tickets fácilmente",
          createSubtitle: "Selecciona un tipo, agrega descripción y envía tu ticket en segundos.",
          profileTitle: "Perfil y ajustes",
          profileSubtitle: "Edita tu cuenta, cambia contraseña y configura tus preferencias."
        },
        desconocido: "Usuario desconocido",
        eliminar: "Eliminar",
        dias: {
          ayer: "Ayer",
          dom: "Dom",
          lun: "Lun",
          mar: "Mar",
          mie: "Mié",
          jue: "Jue",
          vie: "Vie",
          sab: "Sáb"
        },
        mensajes: {
          titulo: "Mensajes",
          vacio: "No tienes conversaciones activas.",
          noEsp: "Problema no especificado",
          proceder: "¿Cómo deseas proceder?",
          elegir: "Elige qué pasará con este ticket de ayuda.",
          abandonar: "Abandonar ayuda",
          libera: "Libera el ticket para aguien más",
          finalizar: "Finalizar como cancelado",
          cierra: "Cierra el ticket permanentemente",
          volver: "Volver al chat",
          resuelto: "¿Problema resuelto?",
          cerrar: "Se cerrará el chat y podrás calificar la atención.",
          siTerminar: "Sí, terminar y calificar",
          seguir: "Seguir en el chat",
          califica: "¡Califica el apoyo!",
          enviar: "Enviar y finalizar",
          place: "Escribe un mensaje...",
          online: "En línea",
          typing: "Escribiendo...",
        },
        profile: {
          newLevel: {
            titulo: '¡Felicidades!',
            mensaje: '¡Has subido al nivel {{newLevel}} - {{levelTitle}}!',
          },
          levelClimb: '¡Subiste de nivel!',
          levelName: {
            1: 'Principiante',
            2: 'Aprendiz',
            3: 'Colaborador',
            4: 'Experto',
            5: 'Mentor Avanzado',
            6: 'Maestro',
            7: 'Leyenda',
            8: 'Ícono',
            9: 'Deidad',
            10: 'Eterno',
            11: 'Inmortal',
            12: 'Supremo',
            13: 'Omnisciente',
            14: 'Trascendental',
            15: 'Divino',
          },
          nivel: 'Nivel',
          activeSince: 'Activo desde {{- date}}',
          semestre: 'Semestre',
          puntos: 'Puntos',
          faltan: 'Faltan {{puntos}} puntos para el siguiente nivel',
          habilidades: 'HABILIDADES',
          estadisticas: {
            titulo: 'ESTADÍSTICAS',
            ayuda: 'Ayudas dadas',
            calificacion: 'Calificación',
            solicitudes: 'Ayudas pedidas',
          },
          seeMore: 'Ver más',
          seeLess: 'Ver menos',
          edit: {
            titulo: "Editar perfil",
            foto: "Editar foto",
            nombre: "NOMBRE",
            nombrePlace: "Tu nombre completo",
            carrera: "CARRERA",
            semestre: "SEMESTRE",
            habilidades: "HABILIDADES",
            selecciona: "Selecciona las áreas en las que puedes apoyar",
            guardar: "Guardar Cambios",
            selectCarrera: "Selecciona tu carrera",
            selectSemestre: "Selecciona tu semestre",
            password: "Cambiar contraseña",
            proteger: "Para proteger tu cuenta, primero verifica tu contraseña actual.",
            actual: "CONTRASEÑA ACTUAL",
            nueva: "NUEVA CONTRASEÑA",
            minimo: "Mínimo 8 caracteres",
            confirmar: "CONFIRMAR NUEVA CONTRASEÑA",
            repite: "Repite la nueva contraseña",
            actualizar: "Actualizar Contraseña",
            req: {
              caracteres: "8+ caracteres",
              mayu: "Mayúscula",
              minu: "Minúscula",
              numero: "Número",
              simbolo: "Símbolo"
            },
            coinciden: "✓ Las contraseñas coinciden",
            noCoinciden: "✗ No coinciden aún",
            error: {
              currentRequired: "Ingresa tu contraseña actual.",
              newRequired: "Ingresa una nueva contraseña.",
              minLength: "Debe tener al menos 8 caracteres.",
              requirements: "Debe incluir mayúscula, minúscula, número y un símbolo.",
              confirmRequired: "Confirma tu nueva contraseña.",
              noMatch: "Las contraseñas no coinciden.",
              currentIncorrect: "La contraseña actual es incorrecta.",
              sessionExpiredTitle: "Sesión expirada",
              sessionExpiredMessage: "Por seguridad, vuelve a iniciar sesión e intenta de nuevo.",
              generic: "No se pudo cambiar la contraseña. Intenta de nuevo."
            },
            successPasswordTitle: "¡Contraseña actualizada!",
            successPasswordMessage: "Tu contraseña fue cambiada exitosamente.",
            strength: {
              debil: "Débil",
              regular: "Regular",
              buena: "Buena",
              fuerte: "Fuerte"
            },
          },
          cerrarSesion: "Cerrar sesión",
          cerrarConfirmacion: "¿Estás seguro de que deseas salir de tu cuenta?",
          si: "Sí, salir",
          errorCerrar: "No se pudo cerrar la sesión.",
          eliminar: "Eliminar cuenta",
          eliminarConfirmacion: "Esta acción es irreversible. ¿Seguro que deseas eliminar tu cuenta?",
          student: "Estudiante",
          carrera: {
            li: 'Licenciatura en Informática',
            lati: 'Licenciatura en Administración de las TI',
            sof: 'Ingeniería de Software',
            ic: 'Ingeniería en Computación',
            itr: 'Ingeniería en Telecomunicaciones y Redes',
            cad: 'Ingeniería en Ciencia y Analítica de Datos',
            itic: 'Ingeniería en Tecnologías de Información y Ciberseguridad',
          }
        },
        home: {
          filtro: 'Filtrar búsqueda',
          noneFound: "No se encontraron tickets con esos filtros.",
        },
        settings: {
          titulo: "Ajustes",
          cuenta: {
            titulo: "CUENTA",
            editar: "Editar datos personales",
            cont: "Cambiar contraseña",
            cont2: "Contraseña",
            idioma: "Idioma"
          },
          notificaciones: {
            titulo: "NOTIFICACIONES",
            push: "Notificaciones push",
            tickets: "Tickets que coinciden",
            insignias: "Nuevas insignias",
            mensajes: "Mensajes nuevos"
          },
          legal: {
            titulo: "LEGAL",
            terminos: "Términos y Condiciones",
            politicas: "Políticas de Privacidad"
          },
          cerrar: "Cerrar Sesión",
          languageUpdatedTitle: "¡Listo!",
          languageUpdatedSuccess: "Tu perfil fue actualizado correctamente.",
          languageUpdatedError: "No se pudo guardar el perfil. Intenta de nuevo.",
          eliminar: {
            titulo: "CUENTA",
            eliminar: "Eliminar Cuenta"
          }
        },
        tickets: {
          titulo: "Mis Tickets",
          gestiona: "Gestiona tus solicitudes y ayudas",
          activos: "activos",
          solicite: "Solicité",
          ayudando: "Ayudando",
          historial: "Historial",
          permanente: "Esta acción es permanente y no se puede deshacer",
          eliminar: "Sí, eliminar",
          masAyuda: "¿Necesitas más ayuda?",
          nuevo: "Crear nuevo ticket",
          sinActivas: "Aún no tienes solicitudes activas",
          sinAyudas: "No estás ayudando a nadie en este momento",
          explorar: "Explorar tickets",
          tuHistorial: "Tu historial aparecerá aquí",
          apoyo: "¡Yo te apoyo!",
          reporte: "¿Por qué consideras que este ticket no es apropiado?",
          reporteDesc: "Describe lo que ocurrió...",
          enChat: "En chat",
          irChat: "Ir al chat",
          abandonar: "Abandonar",
          asignada: "Asignada",
          sinVol: "Sin voluntario aún",
          ayudaPor: "Ayudado por ",
          editar: "Ver y editar",
          ayude: "Ayudé",
          valoracion: "Ver valoración recibida"
        },
        crear: {
          titulo: "Pedir Ayuda",
          subtitulo: "Crea tu ticket",
          subtexto: "Alguien de la facultad puede ayudarte",
          tituloProblema: "TITULO DEL PROBLEMA",
          tituloPlace: "Ej: No entiendo la recursividad en Python",
          tituloDesc: "DESCRIPCIÓN DETALLADA",
          descPlace: "Explica tu duda con más detalle. Entre más info, más fácil es ayudarte...",
          urgencia: "NIVEL DE URGENCIA",
          tags: "ETIQUETAS (MÁX. 3)",
          crear: "Crear Solicitud"
        },
        error: {
          atencion: "Atención",
          seleccionMin: "Favor de seleccionar al menos una etiqueta para la solicitud.",
          faltanDatos: "Faltan datos en el registro.",
          seleccionUrgencia: "Por favor selecciona un nivel de urgencia.",
          sinId: "No se encontró el ID del ticket para actualizar.",
          reporte: "Por favor selecciona un motivo de reporte.",
          reportando: "Reportando:",
          envio: "Reporte enviado",
          recibido: "Hemos recibido tu reporte y lo revisaremos pronto.",
        },
        edit: {
          titulo: "Edita tu ticket",
          subtitulo: "Modifica los detalles de tu solicitud de ayuda",
          guardar: "Guardar Cambios",
          exito: "Editado correctamente",
          exitoMensaje: "Tus cambios han sido guardados."
        },
        prioridad: {
          alta: "Alta",
          media: "Media",
          baja: "Baja",
          normal: "Normal"
        },
        tiempo: {
          segundos: "Hace {{- segundos}} segundos",
          minutos: "Hace {{- minutos}} minutos",
          horas: "Hace {{- horas}} horas",
          dias: "Hace {{- dias}} días",
        },
        badges: {
          firstHelp: "Primer Ayuda",
          firstHelpDesc: "Da tu primera ayuda.",
          firstRequest: "Primera solicitud",
          firstRequestDesc: "Solicita ayuda por primera vez.",
          helper5: "Solidario",
          helper5Desc: "Ayuda a 5 compañeros.",
          dedicado: "Dedicado",
          dedicadoDesc: "Da 10 ayudas en total.",
          top: "Top Tutor",
          topDesc: "Da 25 ayudas en total.",
          helper50: "Leyenda del Campus",
          helper50Desc: "Ayuda a 50 compañeros.",
          helper100: "Pilar Académico",
          helper100Desc: "Ayuda a 100 compañeros. Increíble dedicación.",
          estrellas: "5 Estrellas",
          estrellasDesc: "Mantén una calificación de 5.0",
          rating45: "Excelencia",
          rating45Desc: "Mantén una calificación promedio ≥ 4.5 con al menos 5 ayudas.",
          perfect10: "Perfeccionista",
          perfect10Desc: "Recibe calificación perfecta (5 estrellas) en 10 ayudas consecutivas.",
          streak3: "En racha",
          streak3Desc: "Resuelve 3 tickets seguidos sin abandonar.",
          rachaSiete: "En Racha x7",
          rachaSieteDesc: "Ayuda en 7 tickets consecutivos.",
          streak15: "Imparable",
          streak15Desc: "Resuelve 15 tickets seguidos sin abandonar.",
          rapida: "Respuesta Rápida",
          rapidaDesc: "Responde un ticket en menos de 5 minutos.",
          speedDemon: "Velocista",
          speedDemonDesc: "Resuelve 10 tickets dentro del tiempo límite (speed bonus).",
          expertoDB: "Experto DB",
          expertoDBDesc: "Resuelve 5 tickets de Bases de Datos.",
          mathExpert: "Matemático",
          mathExpertDesc: "Resuelve 5 tickets de Matemáticas.",
          programmingExpert: "Dev Ninja",
          programmingExpertDesc: "Resuelve 5 tickets de Programación.",
          polymath: "Polímata",
          polymathDesc: "Resuelve al menos 1 ticket en 5 categorías diferentes.",
          level3: "Experto certificado",
          level3Desc: "Alcanza el nivel 3 (Experto).",
          nivelCinco: "Nivel 5",
          nivelCincoDesc: "Alcanza el nivel 5.",
          level6: "Héroe del Campus",
          level6Desc: "Alcanza el nivel máximo (Héroe).",
          points100: "Primer centenar",
          points100Desc: "Acumula 100 puntos.",
          points500: "Medio millar",
          points500Desc: "Acumula 500 puntos.",
          points1000: "Millar de oro",
          points1000Desc: "Acumula 1000 puntos.",
          rescuer: "Rescatista",
          rescuerDesc: "Resuelve un ticket de prioridad Alta como usuario nuevo (< 100 pts).",
          comeback: "Resiliencia",
          comebackDesc: "Vuelve a ayudar después de una penalización.",
          nightOwl: "Búho nocturno",
          nightOwlDesc: "Resuelve 3 tickets entre las 10 PM y las 2 AM.",
          desbloq: "¡Insignia desbloqueada!",
          req: "Requisito:"
        },
        notif: {
          titulo: "Notificaciones",
          sinNotif: "No tines notificaciones aún.",
          mensaje: {
            titulo: "¡Alguien quiere ayudarte! 🚀",
            desc: "Han aceptado tu ticket: \"{{ticket}}\""
          },
          match: {
            titulo: "Ticket que coincide con tus habilidades",
            desc: "Alguien necesita ayuda con: {{tags}}"
          }
        },
        skills: {
          programming: 'Programación',
          python: 'Python',
          algebra: 'Álgebra',
          calculus: 'Cálculo',
          design: 'Diseño',
          javascript: 'JavaScript',
          algorithms: 'Algoritmos',
          reactNative: 'React Native',
          nodejs: 'Node.js',
          uxui: 'UX/UI',
          figma: 'Figma',
          recursion: 'Recursión',
          java: 'Java',
          express: 'Express',
          database: 'Base de Datos',
          sql: 'SQL',
          nosql: 'NoSQL',
          aws: 'AWS',
          octave: 'Octave',
        },
        reporte: {
          contenido: 'Contenido inapropiado o adulto',
          solicita: 'Solicita dinero o cobro por la ayuda',
          lenguaje: 'Lenguaje ofensivo o acoso',
          spam: 'Spam o contenido falso',
          otro: 'Otro motivo',
        }
      },
    },
  },
});


export default i18next;