import i18next from 'i18next';

i18next.init({
  fallbackLng: ['es'],
  debug: true,
  resources: {
    en: {
      translation: {
        back: "Back",
        buscar: "Search",
        loading: "Loading...",
        save: "Save",
        loadingSave: "Saving...",
        cancelar: "Cancel",
        terminar: "Finish",
        traducir: "Translate",
        reportar: "Report",
        enviarReporte: "Send Report",
        tutor: "as tutor",
        desconocido: "Unknown user",
        eliminar: "Delete",
        dias: {
          ayer: "Yesterday",
          dom: "Sun",
          lun: "Mon",
          mar: "Tue",
          mie: "Wed",
          jue: "Thu",
          vie: "Fri",
          sab: "Sat"
        },
        mensajes: {
          titulo: "Messages",
          vacio: "You have no active conversations.",
          noEsp: "Problem not specified",
          proceder: "How do you wish to proceed?",
          elegir: "Choose what will happen with this ticket.",
          abandonar: "Abandon help",
          libera: "Free this ticket for someone else",
          finalizar: "Finalize as canceled",
          cierra: "Close the ticket permanentely",
          volver: "Return to chat",
          resuelto: "Problem solved?",
          cerrar: "The chat will be closed, and you will be able to score the help.",
          siTerminar: "Yes, finish and score",
          seguir: "Stay in the chat",
          califica: "Score the help!",
          enviar: "Submit and finalize",
          place: "Write a message...",
        },
        profile: {
          newLevel: {
            titulo: 'Congratulations!',
            mensaje: 'You have reached level {{newLevel}} - {{levelTitle}}!',
          },
          levelClimb: 'You leveled up!',
          levelName: {
            1: 'Beginner',
            2: 'Apprentice',
            3: 'Collaborator',
            4: 'Expert',
            5: 'Advanced Mentor',
            6: 'Master',
            7: 'Legend',
            8: 'Icon',
            9: 'Deity',
            10: 'Eternal',
            11: 'Immortal',
            12: 'Supreme',
            13: 'Omniscient',
            14: 'Transcendent',
            15: 'Divine',
          },
          nivel: 'Level',
          activeSince: 'Active since {{- date}}',
          semestre: 'Semester',
          puntos: 'Points',
          faltan: 'Missing {{puntos}} points for next level',
          habilidades: 'SKILLS',
          estadisticas: {
            titulo: 'STATISTICS',
            ayuda: 'Help given',
            calificacion: 'Rating',
            solicitudes: 'Help requested',
          },
          seeMore: 'See more',
          seeLess: 'See less',
          edit: {
            titulo: "Edit profile",
            foto: "Edit photo",
            nombre: "NAME",
            nombrePlace: "Your full name",
            carrera: "TRACK",
            semestre: "SEMESTER",
            habilidades: "SKILLS",
            selecciona: "Select the areas in which you can help",
            guardar: "Save Changes",
            selectCarrera: "Select your track",
            selectSemestre: "Select your semester",
            password: "Change password",
            proteger: "To protect your account, please verify your current password first.",
            actual: "CURRENT PASSWORD",
            nueva: "NEW PASSWORD",
            minimo: "Minimum 8 characters",
            confirmar: "CONFIRM NEW PASSWORD",
            repite: "Repeat new password",
            actualizar: "Update Password",
            req: {
              caracteres: "8+ characters",
              mayu: "Uppercase",
              minu: "Lowercase",
              numero: "Number",
              simbolo: "Symbol"
            },
            coinciden: "✓ The passwords match",
            noCoinciden: "✗ The passwords don't match yet",
            strength: {
              debil: "Weak",
              regular: "Regular",
              buena: "Good",
              fuerte: "Strong"
            }
          },
          cerrarSesion: "Close session",
          cerrarConfirmacion: "Are you sure you want to close session on this account?",
          si: "Yes, close",
          errorCerrar: "The session could not be closed.",
          eliminar: "Delete account",
          eliminarConfirmacion: "This action is irreversible. Are you sure you want to delete your account?",
        },
        home: {
          filtro: 'Filter your search',
          noneFound: "No tickets were found with those filters.",
        },
        settings: {
          titulo: "Settings",
          cuenta: {
            titulo: "ACCOUNT",
            editar: "Edit personal information",
            cont: "Change password",
            idioma: "Language"
          },
          notificaciones: {
            titulo: "NOTIFICATIONS",
            push: "Push notificationa",
            tickets: "Tickets that match",
            insignias: "New insignias",
            mensajes: "New messages"
          },
          legal: {
            titulo: "LEGAL",
            terminos: "Terms and Conditions",
            politicas: "Privacy Policies"
          },
          cerrar: "Close Session",
          eliminar: {
            titulo: "ACCOUNT",
            eliminar: "Delete Account"
          }
        },
        tickets: {
          titulo: "My Tickets",
          gestiona: "Manage your requests and help",
          activos: "active",
          solicite: "Requests",
          ayudando: "Helping",
          historial: "History",
          permanente: "This action is permanent and cannot be undone",
          eliminar: "Yes, delete",
          masAyuda: "Do you need more help?",
          nuevo: "Create new ticket",
          sinActivas: "You still don't have any active requests",
          sinAyudas: "You are not currently helping anyone",
          explorar: "Explore tickets",
          tuHistorial: "Your history will appear here",
          apoyo: "I'll help you!",
          reporte: "Why do you consider that this ticket is inappropriate?",
          reporteDesc: "Describe what happened...",
          enChat: "In chat",
          irChat: "Go to chat",
          abandonar: "Abandon",
          asignada: "Asigned",
          sinVol: "No volunteer so far",
          ayudaPor: "Helped by ",
          editar: "See and edit",
          ayude: "Helped",
          valoracion: "See score received"
        },
        crear: {
          titulo: "Ask For Help",
          subtitulo: "Create your ticket",
          subtexto: "Someone on campus can help",
          tituloProblema: "PROBLEM TITLE",
          tituloPlace: "Eg: I don't understand recursivity in Python",
          tituloDesc: "DETAILED DESCRIPTION",
          descPlace: "Explain your question in detail. The more info there is, the easier it is to help...",
          urgencia: "URGENCY",
          tags: "TAGS (MAX. 3)",
          crear: "Create request"
        },
        error: {
          atencion: "Attention",
          seleccionMin: "Please select at least one tag for the request.",
          faltanDatos: "Missing fields for the registration.",
          seleccionUrgencia: "Please select a level of urgency.",
          sinId: "Could not find the ID of the ticket to update.",
          reporte: "Please select a reason for reporting.",
          reportando: "Reporting:",
          envio: "Report sent",
          recibido: "We have received your report and we will revise it soon.",
        },
        edit: {
          titulo: "Edit your ticket",
          subtitulo: "Modify the details of your request for help",
          guardar: "Save Changes",
          exito: "Edited correctly",
          exitoMensaje: "Your changes have been saved."
        },
        prioridad: {
          alta: "High",
          media: "Medium",
          baja: "Low",
        },
        tiempo: {
          segundos: "{{- segundos}} seconds ago",
          minutos: "{{- minutos}} minutes ago",
          horas: "{{- horas}} hours ago",
          dias: "{{- dias}} days ago",
        },
        badges: {
          firstHelp: "First Help",
          firstHelpDesc: "Give your first help.",
          rachaSiete: "On Streak x7",
          rachaSieteDesc: "Help with seven consecutive tickets.",
          estrellas: "5 Stars",
          estrellasDesc: "Mantain a score of 5.0",
          rapida: "Fast Response",
          rapidaDesc: "Resolve a ticket in less than 5 minutes.",
          expertoDB: "Expert in DB",
          expertoDBDesc: "Resolve 5 database tickets.",
          top: "Top Tutor",
          topDesc: "Help a total of 25 times.",
          dedicado: "Dedicated",
          dedicadoDesc: "Help a total of 10 times",
          nivelCinco: "Level 5",
          nivelCincoDesc: "Reach level 5.",
          desbloq: "Insignia unlocked!",
          req: "Requirement:",
        },
        notif: {
          titulo: "Notifications",
          sinNotif: "You don't have any notifications yet."
        },
        reporte: {
          contenido: 'Inappropriate or adult content',
          solicita: 'Charges a price for help',
          lenguaje: 'Offensive language',
          spam: 'Spam or false content',
          otro: 'Other',
        }
      },
    },
    es: {
      translation: {
        back: "Regresar",
        buscar: "Buscar",
        loading: "Cargando...",
        save: "Guardar",
        loadingSave: "Guardando...",
        cancelar: "Cancelar",
        terminar: "Terminar",
        traducir: "Traducir",
        reportar: "Reportar",
        enviarReporte: "Enviar Reporte",
        tutor: "como tutor",
        desconocido: "Usuario desconocido",
        eliminar: "Eliminar",
        dias: {
          ayer: "Ayer",
          dom: "Dom",
          lun: "Lun",
          mar: "Mar",
          mie: "Mié",
          jue: "Jue",
          vie: "Vie",
          sab: "Sáb"
        },
        mensajes: {
          titulo: "Mensajes",
          vacio: "No tienes conversaciones activas.",
          noEsp: "Problema no especificado",
          proceder: "¿Cómo deseas proceder?",
          elegir: "Elige qué pasará con este ticket de ayuda.",
          abandonar: "Abandonar ayuda",
          libera: "Libera el ticket para aguien más",
          finalizar: "Finalizar como cancelado",
          cierra: "Cierra el ticket permanentemente",
          volver: "Volver al chat",
          resuelto: "¿Problema resuelto?",
          cerrar: "Se cerrará el chat y podrás calificar la atención.",
          siTerminar: "Sí, terminar y calificar",
          seguir: "Seguir en el chat",
          califica: "¡Califica el apoyo!",
          enviar: "Enviar y finalizar",
          place: "Escribe un mensaje...",
        },
        profile: {
          newLevel: {
            titulo: '¡Felicidades!',
            mensaje: '¡Has subido al nivel {{newLevel}} - {{levelTitle}}!',
          },
          levelClimb: '¡Subiste de nivel!',
          levelName: {
            1: 'Principiante',
            2: 'Aprendiz',
            3: 'Colaborador',
            4: 'Experto',
            5: 'Mentor Avanzado',
            6: 'Maestro',
            7: 'Leyenda',
            8: 'Ícono',
            9: 'Deidad',
            10: 'Eterno',
            11: 'Inmortal',
            12: 'Supremo',
            13: 'Omnisciente',
            14: 'Trascendental',
            15: 'Divino',
          },
          nivel: 'Nivel',
          activeSince: 'Activo desde {{- date}}',
          semestre: 'Semestre',
          puntos: 'Puntos',
          faltan: 'Faltan {{puntos}} puntos para el siguiente nivel',
          habilidades: 'HABILIDADES',
          estadisticas: {
            titulo: 'ESTADÍSTICAS',
            ayuda: 'Ayudas dadas',
            calificacion: 'Calificación',
            solicitudes: 'Ayudas pedidas',
          },
          seeMore: 'Ver más',
          seeLess: 'Ver menos',
          edit: {
            titulo: "Editar perfil",
            foto: "Editar foto",
            nombre: "NOMBRE",
            nombrePlace: "Tu nombre completo",
            carrera: "CARRERA",
            semestre: "SEMESTRE",
            habilidades: "HABILIDADES",
            selecciona: "Selecciona las áreas en las que puedes apoyar",
            guardar: "Guardar Cambios",
            selectCarrera: "Selecciona tu carrera",
            selectSemestre: "Selecciona tu semestre",
            password: "Cambiar contraseña",
            proteger: "Para proteger tu cuenta, primero verifica tu contraseña actual.",
            actual: "CONTRASEÑA ACTUAL",
            nueva: "NUEVA CONTRASEÑA",
            minimo: "Mínimo 8 caracteres",
            confirmar: "CONFIRMAR NUEVA CONTRASEÑA",
            repite: "Repite la nueva contraseña",
            actualizar: "Actualizar Contraseña",
            req: {
              caracteres: "8+ caracteres",
              mayu: "Mayúscula",
              minu: "Minúscula",
              numero: "Número",
              simbolo: "Símbolo"
            },
            coinciden: "✓ Las contraseñas coinciden",
            noCoinciden: "✗ No coinciden aún",
            strength: {
              debil: "Débil",
              regular: "Regular",
              buena: "Buena",
              fuerte: "Fuerte"
            },
          },
          cerrarSesion: "Cerrar sesión",
          cerrarConfirmacion: "¿Estás seguro de que deseas salir de tu cuenta?",
          si: "Sí, salir",
          errorCerrar: "No se pudo cerrar la sesión.",
          eliminar: "Eliminar cuenta",
          eliminarConfirmacion: "Esta acción es irreversible. ¿Seguro que deseas eliminar tu cuenta?",
        },
        home: {
          filtro: 'Filtrar búsqueda',
          noneFound: "No se encontraron tickets con esos filtros.",
        },
        settings: {
          titulo: "Ajustes",
          cuenta: {
            titulo: "CUENTA",
            editar: "Editar datos personales",
            cont: "Cambiar contraseña",
            idioma: "Idioma"
          },
          notificaciones: {
            titulo: "NOTIFICACIONES",
            push: "Notificaciones push",
            tickets: "Tickets que coinciden",
            insignias: "Nuevas insignias",
            mensajes: "Mensajes nuevos"
          },
          legal: {
            titulo: "LEGAL",
            terminos: "Términos y Condiciones",
            politicas: "Políticas de Privacidad"
          },
          cerrar: "Cerrar Sesión",
          eliminar: {
            titulo: "CUENTA",
            eliminar: "Eliminar Cuenta"
          }
        },
        tickets: {
          titulo: "Mis Tickets",
          gestiona: "Gestiona tus solicitudes y ayudas",
          activos: "activos",
          solicite: "Solicité",
          ayudando: "Ayudando",
          historial: "Historial",
          permanente: "Esta acción es permanente y no se puede deshacer",
          eliminar: "Sí, eliminar",
          masAyuda: "¿Necesitas más ayuda?",
          nuevo: "Crear nuevo ticket",
          sinActivas: "Aún no tienes solicitudes activas",
          sinAyudas: "No estás ayudando a nadie en este momento",
          explorar: "Explorar tickets",
          tuHistorial: "Tu historial aparecerá aquí",
          apoyo: "¡Yo te apoyo!",
          reporte: "¿Por qué consideras que este ticket no es apropiado?",
          reporteDesc: "Describe lo que ocurrió...",
          enChat: "En chat",
          irChat: "Ir al chat",
          abandonar: "Abandonar",
          asignada: "Asignada",
          sinVol: "Sin voluntario aún",
          ayudaPor: "Ayudado por ",
          editar: "Ver y editar",
          ayude: "Ayudé",
          valoracion: "Ver valoración recibida"
        },
        crear: {
          titulo: "Pedir Ayuda",
          subtitulo: "Crea tu ticket",
          subtexto: "Alguien de la facultad puede ayudarte",
          tituloProblema: "TITULO DEL PROBLEMA",
          tituloPlace: "Ej: No entiendo la recursividad en Python",
          tituloDesc: "DESCRIPCIÓN DETALLADA",
          descPlace: "Explica tu duda con más detalle. Entre más info, más fácil es ayudarte...",
          urgencia: "NIVEL DE URGENCIA",
          tags: "ETIQUETAS (MÁX. 3)",
          crear: "Crear Solicitud"
        },
        error: {
          atencion: "Atención",
          seleccionMin: "Favor de seleccionar al menos una etiqueta para la solicitud.",
          faltanDatos: "Faltan datos en el registro.",
          seleccionUrgencia: "Por favor selecciona un nivel de urgencia.",
          sinId: "No se encontró el ID del ticket para actualizar.",
          reporte: "Por favor selecciona un motivo de reporte.",
          reportando: "Reportando:",
          envio: "Reporte enviado",
          recibido: "Hemos recibido tu reporte y lo revisaremos pronto.",
        },
        edit: {
          titulo: "Edita tu ticket",
          subtitulo: "Modifica los detalles de tu solicitud de ayuda",
          guardar: "Guardar Cambios",
          exito: "Editado correctamente",
          exitoMensaje: "Tus cambios han sido guardados."
        },
        prioridad: {
          alta: "Alta",
          media: "Media",
          baja: "Baja",
        },
        tiempo: {
          segundos: "Hace {{- segundos}} segundos",
          minutos: "Hace {{- minutos}} minutos",
          horas: "Hace {{- horas}} horas",
          dias: "Hace {{- dias}} días",
        },
        badges: {
          firstHelp: "Primer Ayuda",
          firstHelpDesc: "Da tu primera ayuda.",
          rachaSiete: "En Racha x7",
          rachaSieteDesc: "Ayuda en 7 tickets consecutivos.",
          estrellas: "5 Estrellas",
          estrellasDesc: "Mantén una calificación de 5.0",
          rapida: "Respuesta Rápida",
          rapidaDesc: "Responde un ticket en menos de 5 minutos.",
          expertoDB: "Experto DB",
          expertoDBDesc: "Resuelve 5 tickets de Bases de Datos.",
          top: "Top Tutor",
          topDesc: "Da 25 ayudas en total.",
          dedicado: "Dedicado",
          dedicadoDesc: "Da 10 ayudas en total.",
          nivelCinco: "Nivel 5",
          nivelCincoDesc: "Alcanza el nivel 5.",
          desbloq: "¡Insignia desbloqueada!",
          req: "Requisito:",
        },
        notif: {
          titulo: "Notificaciones",
          sinNotif: "No tines notificaciones aún."
        },
        reporte: {
          contenido: 'Contenido inapropiado o adulto',
          solicita: 'Solicita dinero o cobro por la ayuda',
          lenguaje: 'Lenguaje ofensivo o acoso',
          spam: 'Spam o contenido falso',
          otro: 'Otro motivo',
        }
      },
    },
  },
});


export default i18next;